### ISSUE TITLE
editbox 安卓上将游戏置到后台后，再打开游戏，点击editbox就无法再调起软键盘

### ISSUE THREAD

**Issue by lezard618** [u0u0/Cocos2d-Lua-Community#12]
调查了下是再次将CocosAcitvity放到前台的时候，被重新创建了，所以就丢失了java侧的editbox，但是从c++重新创建了对应的java的editbox过后，发现新创建的java侧的editbox无法获取焦点focus，所以永远没法调起键盘。

不知道有没有什么解决方案

**Comment by u0u0** [comment]
暂时没有～～
