### ISSUE TITLE
void Widget::updateSizeAndPosition() 没有判断空指针

### ISSUE THREAD

**Issue by wenxue0501** [u0u0/Cocos2d-Lua-Community#18]
void Widget::updateSizeAndPosition()
{
	if (_parent) //空指针判断
	{
		Size pSize = _parent->getContentSize();
		updateSizeAndPosition(pSize);
	}
}

**Comment by u0u0** [comment]
fixed https://github.com/u0u0/Cocos2d-Lua-Community/commit/e02012210f6ae4b22e93e34fa5a1f6fc3c159120.
