### ISSUE TITLE
gradle 升级到 7.x

### ISSUE THREAD

**Issue by shengdoushi** [u0u0/Cocos2d-Lua-Community#19]
升级到 7.x 后, 
1.  gradle wrapper 升级: gradlew, gradlew.bat, gradle/wrapper/gradle-wrapper.jar
2. 更新 settings.gradle, build.gradle 两个文件内容格式稍作调整

**Comment by u0u0** [comment]
https://github.com/u0u0/Cocos2d-Lua-Community/commit/0f7a405ca7e272ed244043e6e04dae17225523fe
