### ISSUE TITLE
在安卓真机上运行时，随机出现

### ISSUE THREAD

**Issue by fx843580946** [u0u0/Cocos2d-Lua-Community#23]
![1943274268](https://github.com/u0u0/Cocos2d-Lua-Community/assets/23655941/e3acd927-843e-44d4-a5ab-b08710519ae9)

**Comment by u0u0** [comment]
单凭这点信息是无法调试的。

**Comment by fx843580946** [comment]
您发的邮件我已收到，谢谢····

**Comment by fx843580946** [comment]
#00 pc 000000000066b89c /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (cocos2d::Texture2D::hasPremultipliedAlpha() const+0) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
2
#01 pc 0000000000741a48 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (spine::SkeletonRenderer::draw(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+2432) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
3
#02 pc 00000000005d5550 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (cocos2d::Node::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+376) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
4
#03 pc 00000000005d5524 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (cocos2d::Node::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+332) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
5
#04 pc 000000000078c130 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (fairygui::FUIContainer::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+1068) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
6
#05 pc 00000000005d5524 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (cocos2d::Node::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+332) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
7
#06 pc 00000000005d5524 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (cocos2d::Node::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+332) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
8
#07 pc 000000000078bf70 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (fairygui::FUIContainer::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+620) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
9
#08 pc 00000000005d5524 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (cocos2d::Node::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+332) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
10
#09 pc 00000000005d5524 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (cocos2d::Node::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+332) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
11
#10 pc 000000000078bf70 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (fairygui::FUIContainer::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+620) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
12
#11 pc 00000000005d5524 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (cocos2d::Node::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+332) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
13
#12 pc 00000000005d5524 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (cocos2d::Node::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+332) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
14
#13 pc 000000000078bf70 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (fairygui::FUIContainer::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+620) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
15
#14 pc 00000000005d5524 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (cocos2d::Node::visit(cocos2d::Renderer*, cocos2d::Mat4 const&, unsigned int)+332) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
16
#15 pc 00000000005f7ed4 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (cocos2d::Scene::render(cocos2d::Renderer*, cocos2d::Mat4 const&, cocos2d::Mat4 const*)+296) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
17
#16 pc 0000000000695fdc /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (cocos2d::Director::drawScene()+372) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
18
#17 pc 0000000000698350 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/lib/arm64/libcocos2dlua.so (cocos2d::Director::mainLoop()+128) [arm64-v8a::e350041220e376f4ed8f2a3644e78114]
19
#18 pc 000000000003a3b0 /data/app/~~3YZ0fgO7w3HjiwdNGBp_4A==/com.game.sang-WNECc16zo-nsYn2lRx0doQ==/oat/arm64/base.odex [arm64-v8a::a3c993c90c2eb15843c57632996e7452]
20
java:
21
org.cocos2dx.lib.Cocos2dxRenderer.onDrawFrame(Cocos2dxRenderer.java:8)
22
android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1589)
23
android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1280)


创建一个骨骼动画，添加在fairygui的一个节点上，会偶现上面的这种情况

**Comment by u0u0** [comment]
这个是fairygui的付费功能，我没怎么测试过。你加群361920466讨论，把测试demo发给我，github issue我关注得少。
