### ISSUE TITLE
在lua中调用了cc.Director:getInstance():getScheduler():unscheduleScriptEntry(schedule)后崩溃

### ISSUE THREAD

**Issue by magicshojo** [u0u0/Cocos2d-Lua-Community#27]
这是安卓上日志
1	#00 pc 000000006966a780 /data/app/~~89KzeIWwaYuXKdD4-H3Mvw==/com.aaa-w77VPHcjvU9pfdr70RRtNw==/base.apk (typeinfo for cocos2d::Timer+0)
2	#01 pc 0000000068a3c960 /data/app/~~89KzeIWwaYuXKdD4-H3Mvw==/com.aaa-w77VPHcjvU9pfdr70RRtNw==/base.apk (fairygui::UIEventDispatcher::doDispatch(int, fairygui::EventContext*)+188)
3	#02 pc 0000000068a3cc14 /data/app/~~89KzeIWwaYuXKdD4-H3Mvw==/com.aaa-w77VPHcjvU9pfdr70RRtNw==/base.apk (fairygui::UIEventDispatcher::doBubble(int, fairygui::EventContext*)+88)
4	#03 pc 0000000068a3cb60 /data/app/~~89KzeIWwaYuXKdD4-H3Mvw==/com.aaa-w77VPHcjvU9pfdr70RRtNw==/base.apk (fairygui::UIEventDispatcher::bubbleEvent(int, void*, cocos2d::Value const&)+120)
5	#04 pc 0000000068a39f78 /data/app/~~89KzeIWwaYuXKdD4-H3Mvw==/com.aaa-w77VPHcjvU9pfdr70RRtNw==/base.apk (fairygui::InputProcessor::onTouchEnded(cocos2d::Touch*, cocos2d::Event*)+1020)
6	#05 pc 0000000068cd521c /data/app/~~89KzeIWwaYuXKdD4-H3Mvw==/com.aaa-w77VPHcjvU9pfdr70RRtNw==/base.apk
7	#06 pc 0000000068cd05c4 /data/app/~~89KzeIWwaYuXKdD4-H3Mvw==/com.aaa-w77VPHcjvU9pfdr70RRtNw==/base.apk (cocos2d::EventDispatcher::dispatchTouchEventToListeners(cocos2d::EventDispatcher::EventListenerVector*, std::__ndk1::function<bool (cocos2d::EventListener*)> const&)+480)
8	#07 pc 0000000068cd0e7c /data/app/~~89KzeIWwaYuXKdD4-H3Mvw==/com.aaa-w77VPHcjvU9pfdr70RRtNw==/base.apk (cocos2d::EventDispatcher::dispatchTouchEvent(cocos2d::EventTouch*)+588)
9	#08 pc 0000000068cd0894 /data/app/~~89KzeIWwaYuXKdD4-H3Mvw==/com.aaa-w77VPHcjvU9pfdr70RRtNw==/base.apk (cocos2d::EventDispatcher::dispatchEvent(cocos2d::Event*)+176)
10	#09 pc 0000000068c52bc0 /data/app/~~89KzeIWwaYuXKdD4-H3Mvw==/com.aaa-w77VPHcjvU9pfdr70RRtNw==/base.apk (cocos2d::GLView::handleTouchesOfEndOrCancel(cocos2d::EventTouch::EventCode, int, long*, float*, float*)+620)
11	#10 pc 00000000686a2898 /data/app/~~89KzeIWwaYuXKdD4-H3Mvw==/com.aaa-w77VPHcjvU9pfdr70RRtNw==/base.apk (Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeTouchesEnd+72)
12	#11 pc 000000000021a354 /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) [arm64-v8a::ea426a52ab3b103f5bedcf9f47097e92]
13	#12 pc 0000000000209a9c /apex/com.android.art/lib64/libart.so (nterp_helper+1948) [arm64-v8a::ea426a52ab3b103f5bedcf9f47097e92]
14	#13 pc 000000000020a254 /apex/com.android.art/lib64/libart.so (nterp_helper+3924) [arm64-v8a::ea426a52ab3b103f5bedcf9f47097e92]
15	#14 pc 00000000a8ed2c34 <unknown>
16	java:
17	org.cocos2dx.lib.Cocos2dxRenderer.handleActionUp(Cocos2dxRenderer.java:131)
18	org.cocos2dx.lib.Cocos2dxGLSurfaceView$10.run(Cocos2dxGLSurfaceView.java:312)
19	android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1502)
20	android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

**Comment by u0u0** [comment]
fgui控件事件中？建议延迟一桢调用，看是否经解决问题。
